package servlets;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

@WebServlet("/Init")
public class MainServlet extends HttpServlet {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	protected void doPost(HttpServletRequest request, HttpServletResponse response)
			throws IOException, ServletException {

		String url = "jdbc:hsqldb:hsql://localhost/workdb";
		String createTableSql = "CREATE TABLE USERS (" + "ID INT GENERATED BY DEFAULT AS IDENTITY,"
				+ " USERNAME VARCHAR(30)," + " PASSWORD VARCHAR(15),"+"EMAIL VARCHAR(120)," + " LEVEL VARCHAR(8)," + " PRIMARY KEY (ID))";
		String login = request.getParameter("login");
		String register = request.getParameter("register");
		try {
			Connection connection = DriverManager.getConnection(url);
			Statement createTable = connection.createStatement();
			ResultSet rs = connection.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while (rs.next()) {
				if (rs.getString("TABLE_NAME").equalsIgnoreCase("USERS")) {
					tableExists = true;
					break;
				}
			}
			if (!tableExists) {
				createTable.executeUpdate(createTableSql);
			}
			createTable.close();
			connection.close();
		} catch (SQLException e) {
			e.printStackTrace();
		}

		if (register != null) {
			response.sendRedirect("/Register.jsp");
		} else if(login != null) {
			response.sendRedirect("/Login.jsp");
		}
	}
}
